server:
  port: 8081
spring:
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5433/order-db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/ecommerce-realm
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
order:
  enabled: true

management:
  health:
    circuitbreakers:
      enabled: true


  endpoints:
    web:
      exposure:
        include: "refresh, health, circuitbreakers"
resilience4j:
  circuitbreaker:
    instances:
      inventory:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      inventory:
        maxRetryAttempts: 3
        waitDuration: 2s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
