spring:
  application:
    name: config-serve
  cloud:
    config:
      server:
        git:
          # 1. La URI debe ser estrictamente la ruta raíz del repositorio (la que termina en .git)
          uri: https://github.com/ricardoIsmael/eccomerce-backend.git

          # 2. Le decimos a Spring en qué rama buscar
          default-label: master

          clone-on-start: true

          # 3. AQUÍ ESTÁ LA MAGIA: Le decimos en qué subcarpeta están los .yml
          search-paths: config-data

server:
  port: 8888